# Generated by Django 2.2 on 2019-06-23 13:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20190623_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ツイートID')),
                ('tweet', models.TextField(verbose_name='ツイート')),
                ('picture', models.ImageField(upload_to='timeline', verbose_name='ツイート画像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account', verbose_name='ユーザーID')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='いいねID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('tweet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.Tweet', verbose_name='ツイートID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account', verbose_name='ユーザーID')),
            ],
        ),
    ]
