# Generated by Django 2.2 on 2019-06-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_auto_20190624_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='ツイート画像'),
        ),
    ]
