# Generated by Django 2.2 on 2019-06-28 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0005_auto_20190628_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ids', to='accounts.Account', verbose_name='ユーザーID'),
        ),
    ]
