# Generated by Django 2.2 on 2019-07-02 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0006_auto_20190628_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='tweet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweet_ids', to='timeline.Tweet', verbose_name='ツイートID'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_ids', to='accounts.Account', verbose_name='ユーザーID'),
        ),
    ]
