# Generated by Django 2.2 on 2019-06-23 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ユーザID')),
                ('profile', models.TextField(blank=True, verbose_name='プロフィール')),
                ('background_image', models.ImageField(upload_to='users', verbose_name='背景画像')),
                ('profile_image', models.ImageField(upload_to='users', verbose_name='プロフィール画像')),
                ('total_following', models.IntegerField(verbose_name='フォロー数')),
                ('total_followers', models.IntegerField(verbose_name='フォローワー数')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('follower_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account', verbose_name='ユーザーID')),
            ],
            options={
                'unique_together': {('following_id', 'follower_id', 'updated_at')},
            },
        ),
    ]
