# Generated by Django 2.2 on 2019-06-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='background_image',
            field=models.ImageField(upload_to='accounts', verbose_name='背景画像'),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(upload_to='accounts', verbose_name='プロフィール画像'),
        ),
    ]
