# Generated by Django 2.2 on 2019-06-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190623_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='background_image',
            field=models.ImageField(upload_to='', verbose_name='背景画像'),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(upload_to='', verbose_name='プロフィール画像'),
        ),
    ]
