# Generated by Django 2.2 on 2019-06-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190624_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='匿名希望', max_length=255, verbose_name='名前'),
        ),
    ]
