# Generated by Django 2.2 on 2019-06-27 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190625_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='follower_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='accounts.Account', verbose_name='フォローワーID'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='following_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='accounts.Account', verbose_name='フォローID'),
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='user_id',
        ),
    ]
