# Generated by Django 2.2 on 2019-07-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190628_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='background_image',
            field=models.ImageField(default='media/twitter.jpg', upload_to='', verbose_name='背景画像'),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(default='media/egg.jpg', upload_to='', verbose_name='プロフィール画像'),
        ),
    ]
