# Generated by Django 2.2 on 2019-07-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190704_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='background_image',
            field=models.ImageField(default='twitter.jpg', upload_to='', verbose_name='背景画像'),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(default='egg.jpg', upload_to='', verbose_name='プロフィール画像'),
        ),
    ]
